# Generated by Django 4.2.3 on 2023-07-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barrioprivado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='sector',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='barrioprivado.sector'),
        ),
    ]
