# Generated by Django 4.2.3 on 2023-07-26 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barrioprivado', '0003_rename_codigo_sector_sector_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitado',
            name='residente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='barrioprivado.residente', verbose_name='Nombre del Inquilino'),
        ),
    ]
